package view.frame;

import control.Kundenverwaltung;
import model.kunde.AKunde;
import model.kunde.Adresse;
import util.Helper;

/**
 * Diese Klasse bildet ein Unterfenster für das Ändern eines Kunden ab.
 *
 * @author Malte Dammann
 * E-Mail: s0549309@htw-berlin.de
 * Bearbeitungszeitraum: 05.06.15 - 22.06.2015
 *
 * Modul: Programmierung 2
 *
 * Dateiname: Engine.java
 * IDE: NetBeans IDE 8.0.2
 * Java: 1.8.0_20; Java HotSpot(TM) 64-Bit
 *
 * @since 2015-05-06
 * @version 0.2
 *
 */
public class KundeAendern extends javax.swing.JFrame {

    AKunde aKunde;
    Kundenverwaltung kv;

    /**
     * Konstruktor des Fensters
     *
     * @param nr
     * @param kv
     */
    public KundeAendern(int nr, Kundenverwaltung kv) {
        initComponents();
        this.setTitle("Kunde ändern");
        Helper.getFrameCenter(this);
        initKunde(nr, kv);
        this.setVisible(true);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        this.setAlwaysOnTop( false );
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdresse = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtStraße = new javax.swing.JTextField();
        txtPLZ = new javax.swing.JTextField();
        txtOrt = new javax.swing.JTextField();
        lblRabatt = new javax.swing.JLabel();
        txtRabatt = new javax.swing.JTextField();
        btnSpeichern = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        lblAdresse.setText("Adresse:");

        txtName.setText("Name");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtStraße.setText("Straße + HNr");
        txtStraße.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStraßeActionPerformed(evt);
            }
        });

        txtPLZ.setText("PLZ");
        txtPLZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPLZActionPerformed(evt);
            }
        });

        txtOrt.setText("Ort");
        txtOrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrtActionPerformed(evt);
            }
        });

        lblRabatt.setText("Rabatt:");

        txtRabatt.setText("Rabatt");
        txtRabatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRabattActionPerformed(evt);
            }
        });

        btnSpeichern.setLabel("Speichern");
        btnSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeichernActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStraße, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPLZ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addComponent(txtOrt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdresse)
                            .addComponent(lblRabatt))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtRabatt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSpeichern, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblAdresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStraße, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPLZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(lblRabatt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRabatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnSpeichern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtStraßeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStraßeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStraßeActionPerformed

    private void txtPLZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPLZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPLZActionPerformed

    private void txtOrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrtActionPerformed

    private void txtRabattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRabattActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRabattActionPerformed

    private void btnSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeichernActionPerformed
        speichern(aKunde);
        this.dispose();
    }//GEN-LAST:event_btnSpeichernActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnSpeichern;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblRabatt;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrt;
    private javax.swing.JTextField txtPLZ;
    private javax.swing.JTextField txtRabatt;
    private javax.swing.JTextField txtStraße;
    // End of variables declaration//GEN-END:variables

    private void initKunde(int nr, Kundenverwaltung kv_v) {
        aKunde = kv_v.getListe().get(nr);
        kv = kv_v;
        txtName.setText(aKunde.getAnschrift().getName());
        txtOrt.setText(aKunde.getAnschrift().getOrt());
        txtPLZ.setText(aKunde.getAnschrift().getPlz());
        txtStraße.setText(aKunde.getAnschrift().getStrasse_hnr());
        txtRabatt.setText(String.valueOf(aKunde.getRabatt()));
    }

    private void speichern(AKunde kunde) {
        Adresse adresse = new Adresse(txtName.getText(), txtStraße.getText(), txtPLZ.getText(), txtOrt.getText());
        Double rabatt = Double.valueOf(txtRabatt.getText());
        kv.aendernKunde(kunde, rabatt, adresse);
    }

}
