package view.frame;

import control.Kundenverwaltung;
import model.kunde.AKunde;
import model.kunde.Adresse;
import model.kunde.Endverbraucher;
import model.kunde.GesellschaftMitLiz;
import model.kunde.Grossverbraucher;
import util.Helper;

/**
 * Diese Klasse bildet ein Unterfenster für das Hinzufügen eines Kunden ab.
 *
 * @author Malte Dammann
 * E-Mail: s0549309@htw-berlin.de
 * Bearbeitungszeitraum: 05.06.15 - 22.06.2015
 *
 * Modul: Programmierung 2
 *
 * Dateiname: Engine.java
 * IDE: NetBeans IDE 8.0.2
 * Java: 1.8.0_20; Java HotSpot(TM) 64-Bit
 *
 * @since 2015-05-06
 * @version 0.2
 *
 */
public class NeuerKundeFrame extends javax.swing.JFrame {

    Kundenverwaltung kv;
    int kundenart;
    String name;
    String ort;
    String plz;
    String strasse;
    Double rabatt;

    /**
     * Konstruktor des Fensters
     */
    public NeuerKundeFrame(Kundenverwaltung kv) {
        initComponents();
        initKunde(kv);
        this.setTitle("Kunde anlegen");
        Helper.getFrameCenter(this);
        this.setVisible(true);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        this.setAlwaysOnTop( false );
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupKunden = new javax.swing.ButtonGroup();
        txtRabatt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAdresse = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStraße = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtPLZ = new javax.swing.JTextField();
        txtOrt = new javax.swing.JTextField();
        lblRabatt = new javax.swing.JLabel();
        btnNeu = new java.awt.Button();
        jRadioEndverbraucher = new javax.swing.JRadioButton();
        jRadioGrossverbraucher = new javax.swing.JRadioButton();
        jRadioGesellschaft = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        buttonGroupKunden.add(jRadioEndverbraucher);
        buttonGroupKunden.add(jRadioGrossverbraucher);
        buttonGroupKunden.add(jRadioGesellschaft);
        jRadioEndverbraucher.setSelected(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        txtRabatt.setText("Rabatt");
        txtRabatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRabattActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("Straße:");

        jLabel3.setText("PLZ:");

        lblAdresse.setText("Adresse:");

        jLabel4.setText("Ort:");

        txtName.setText("Name");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel5.setText("%");

        txtStraße.setText("Straße + HNr");
        txtStraße.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStraßeActionPerformed(evt);
            }
        });

        txtPLZ.setText("PLZ");
        txtPLZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPLZActionPerformed(evt);
            }
        });

        txtOrt.setText("Ort");
        txtOrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrtActionPerformed(evt);
            }
        });

        lblRabatt.setText("Rabatt:");

        btnNeu.setLabel("Speichern");
        btnNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeuActionPerformed(evt);
            }
        });

        jRadioEndverbraucher.setText("Endverbraucher");
        jRadioEndverbraucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEndverbraucherActionPerformed(evt);
            }
        });

        jRadioGrossverbraucher.setText("Großverbraucher");
        jRadioGrossverbraucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGrossverbraucherActionPerformed(evt);
            }
        });

        jRadioGesellschaft.setText("Lizenz-Gesellschaft");
        jRadioGesellschaft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGesellschaftActionPerformed(evt);
            }
        });

        jLabel6.setText("Kundenart:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOrt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPLZ, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStraße, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRabatt)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioEndverbraucher)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRabatt, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(jRadioGesellschaft)
                            .addComponent(jRadioGrossverbraucher))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdresse)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStraße, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPLZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRabatt)
                    .addComponent(txtRabatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioEndverbraucher)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioGesellschaft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioGrossverbraucher)
                .addGap(27, 27, 27)
                .addComponent(btnNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRabattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRabattActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRabattActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtStraßeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStraßeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStraßeActionPerformed

    private void txtPLZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPLZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPLZActionPerformed

    private void txtOrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrtActionPerformed

    private void btnNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNeuActionPerformed

    private void jRadioEndverbraucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEndverbraucherActionPerformed
        kundenart = 1;
    }//GEN-LAST:event_jRadioEndverbraucherActionPerformed

    private void jRadioGesellschaftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGesellschaftActionPerformed
        kundenart = 3;
    }//GEN-LAST:event_jRadioGesellschaftActionPerformed

    private void jRadioGrossverbraucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGrossverbraucherActionPerformed
        kundenart = 2;
    }//GEN-LAST:event_jRadioGrossverbraucherActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnNeu;
    private javax.swing.ButtonGroup buttonGroupKunden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioEndverbraucher;
    private javax.swing.JRadioButton jRadioGesellschaft;
    private javax.swing.JRadioButton jRadioGrossverbraucher;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblRabatt;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrt;
    private javax.swing.JTextField txtPLZ;
    private javax.swing.JTextField txtRabatt;
    private javax.swing.JTextField txtStraße;
    // End of variables declaration//GEN-END:variables

    private void initKunde(Kundenverwaltung kv_v) {
        kv = kv_v;
        name = txtName.getText();
        ort = txtOrt.getText();
        plz = txtPLZ.getText();
        strasse = txtStraße.getText();
        rabatt = Double.valueOf(txtRabatt.getText());
    }

    private void anlegen() {
        AKunde kunde;
        switch (kundenart) {
            case 1:
                kunde = new Endverbraucher(new Adresse(name, strasse, plz, ort), rabatt, true);
                kv.neuEndverbraucher(kunde);
                break;
            case 2:
                kunde = new Grossverbraucher(new Adresse(name, strasse, plz, ort), rabatt, 1);
                kv.neuEndverbraucher(kunde);
                break;
            case 3:
                kunde = new GesellschaftMitLiz(new Adresse(name, strasse, plz, ort), rabatt, 1);
                kv.neuEndverbraucher(kunde);
                break;
            default:
                break;
        }
    }

}
